### PR TITLE
fix whitespace creation

### PR DESCRIPTION
**Pull request by yoshuawuyts**
This should fix https://github.com/shama/bel/issues/72

### patch notes
- now creates strings on the server, leading to a 10x speed improvement for rendering
- detects if in Electron, Node, or browser and runs the right version
- fixes random text node creation in lists

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Ok, so right now things are not solved. The current state is:
- browser tests pass, behavior is patched
- server tests fail, we now rely on `.lastChild` in the critical path and `min-document` does not recognize that
- this means that running code on the server could already fail, but it wasn't caught by the tests

What I'm thinking we should do:
- unpublish the last version: it's broken and oh no that's not good
- merge the patch in this PR to master
- split browser & server code, and replace server code with https://github.com/shuhei/pelo/blob/master/index.js

We should get a 10x server render improvement in the process, but also do a semver major release. With that happening we could get cheeky and also add https://github.com/shama/bel/pull/69.

I have a feeling this is a fair amount of changes, so input would be greatly appreciated! Thanks heaps!

---

### IRC dump
```txt
02:55 <yoshuawuyts> URGH
02:55 <yoshuawuyts> ok, so I got this whole mad thing working in the browser - fixed the regression
02:55 <yoshuawuyts> (talking about `bel`)
02:55 <yoshuawuyts> but now the server is failing
02:56 <yoshuawuyts> and worse: it's failing because of a pre-existing bug in `bel` - e.g. min-document is an incomplete DOM implementation, and stuff like .nodeValue and .lastChild does not exist
02:57 <yoshuawuyts> so either: 1) we do a revert and pretend nothing changed. This will disallow child-node reordering tho. Or 2) we merge and break server rendering
02:57 <yoshuawuyts> I'm not thrilled about either option
02:59 <yoshuawuyts> well, technically we're not breaking server rendering - it's already broken - it just makes it, err, well more apparent
03:00 <yoshuawuyts> could be a cool opportunity to complete move to https://github.com/shuhei/pelo btw
03:00 <yoshuawuyts> option 3?
03:00 <yoshuawuyts> (anyone got thoughts on this?)
03:05 <sethvincent> would it be worth working on min-document or an alternative?
03:07 <yoshuawuyts> sethvincent: pelo uses string concatenation which provides a 20x speed improvement over object based approaches. I think if we're going to change anything specifically for server stuff that'd be the clearest path
03:07 <sethvincent> hmm, that makes sense
```

**Comment by yoshuawuyts** [comment]
woot, it works!

**Comment by yoshuawuyts** [comment]
Ok, so we're now running `pelo` in node / electron main process, and regular ol' `bel` code in electron renderer / browser. This means we got a 10x or so perf improvement for rendering in Node. Yay!

Semver major because the intermediate representation on the server also changed. Thanks!

**Comment by mantoni** [comment]
That little whitspace fix got out of hand, right? 😆

**Comment by yoshuawuyts** [comment]
`v5.0.0`

**Pull request merged**
